### ISSUE TITLE
Fix layout shift in NovelTabs component

### ISSUE THREAD

**Issue by panov-aleksey-saritasa** [vndbre/vndbre#19]
This was mentioned in https://github.com/vndbre/vndbre/pull/14#pullrequestreview-749823296
Do you have any ideas or suggestions how it can be fixed?

**Comment by moetazaneta** [comment]
The easiest way is to move hack from `.link` to element with text.

**Comment by moetazaneta** [comment]
I came up with this:
```tsx
const textElement = <span title={title} className={styles.text}>{title}</span>;

<NavLink
  to={to}
  end={end}
  className={({ isActive }) => getNavLinkClassNames(isActive)}
>
  {textElement}
  {badgeElement}
</NavLink>
```

```css
.text {
  display: inline-block;
}
.text::after {
  display: block;
  content: attr(title);
  font-weight: var(--chakra-fontWeights-semibold);
  height: 0px;
  color: transparent;
  overflow: hidden;
  visibility: hidden;
}
```
