### ISSUE TITLE
NovelTab badge wrapping bug

### ISSUE THREAD

**Issue by moetazaneta** [vndbre/vndbre#20]
In #14 when not enough space this happen:
![image](https://user-images.githubusercontent.com/44553669/132638851-d797a47e-8806-4fb5-815e-3cff18905c3b.png)

I came up with a solution:
```css
.link {
  ...
  white-space: nowrap;
}
```
